name    'DanielRedOak-lumberjack'
version '0.0.4'
source 'https://github.com/DanielRedOak/puppet-lumberjack'
author 'DanielRedOak'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring logstash-forwarder'
description 'Module for managing and configuring logstash-forwarder, forked from electrical and MixMuffins' modules on GitHub'
project_page 'https://github.com/DainelRedOak/puppet-lumberjack'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
